services:
  db:
    container_name: kyoso-postgres
    image: postgres:18-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    container_name: kyoso-redis
    image: redis:8-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 128mb --appendonly yes
    ports:
      - 6380:6379

  rustfs:
    container_name: kyoso-rustfs
    image: rustfs/rustfs:latest
    restart: always
    environment:
      - RUSTFS_ALLOW_INSECURE_DEFAULT_CREDENTIALS=true
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - rustfs_data:/data

volumes:
  pg_data:
  redis_data:
  rustfs_data:
